name: kelunga
description: A tamil audio app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  cloud_firestore: ^2.2.0
  firebase_dynamic_links: ^2.0.3
  # firebase_messaging: ^9.1.4
  firebase_analytics: ^8.0.4
  google_sign_in: ^5.0.3

  # Audio
  just_audio: ^0.7.4+1
  audio_service: ^0.17.0
  audio_session: ^0.1.0

  # State Management
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0

  # Dependency Injection
  get_it: ^7.1.3
  injectable: ^1.4.0

  # Caching
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  # UI
  cached_network_image: ^3.0.0-nullsafety
  carousel_slider: ^4.0.0-nullsafety.0
  sliding_up_panel: ^2.0.0+1

  # Logs
  logger: ^1.0.0

  # Route
  auto_route: ^2.2.0

  # Misc
  duration: ^3.0.6
  freezed_annotation: ^0.14.2
  dartz: ^0.10.0-nullsafety.2
  intl: ^0.17.0
  rxdart: ^0.26.0
  url_launcher: ^6.0.3
  in_app_update: ^2.0.0
  in_app_review: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Launcher icon generator
  flutter_launcher_icons: ^0.9.0

  # Code generators
  auto_route_generator: ^2.1.0
  freezed: ^0.14.2
  injectable_generator: ^1.4.0
  build_runner: ^2.0.3

  # Linting
  effective_dart: ^1.3.1

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/app_icon.png'

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900

  assets:
    - assets/images/