name: kelunga
description: A tamil audio app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.3

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  firebase_dynamic_links: ^4.0.3
  # firebase_messaging: ^9.1.4
  firebase_analytics: ^9.0.4
  google_sign_in: ^5.2.1

  # Audio
  just_audio: ^0.9.18
  just_audio_background: ^0.0.1-beta.2
  audio_session: ^0.1.6+1

  # State Management
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0

  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^1.5.0

  # Caching
  hive: ^2.0.5
  hive_flutter: ^1.1.0

  # UI
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  sliding_up_panel: ^2.0.0+1

  # Logs
  logger: ^1.1.0

  # Route
  auto_route: ^3.2.0

  # Misc
  share_plus: ^3.0.4
  duration: ^3.0.8
  freezed_annotation: ^1.1.0
  dartz: ^0.10.0-nullsafety.2
  intl: ^0.17.0
  rxdart: ^0.27.3
  url_launcher: ^6.0.17
  in_app_update: ^2.0.0
  in_app_review: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Launcher icon generator
  flutter_launcher_icons: ^0.9.2

  # Code generators
  auto_route_generator: ^3.2.0
  freezed: ^1.1.0
  injectable_generator: ^1.5.2
  build_runner: ^2.1.7

  # Linting
  flutter_lints: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900

  assets:
    - assets/images/
